# Generated by Django 4.2.7 on 2023-11-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunek',
            name='filmy',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Gatunek',
        ),
        migrations.DeleteModel(
            name='Osoba',
        ),
    ]
