# Generated by Django 4.2.6 on 2023-10-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0002_film_rokprodukcji_alter_film_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='filmwebRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='obraz',
            field=models.ImageField(blank=True, null=True, upload_to='obrazy'),
        ),
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.TextField(default=''),
        ),
    ]
