# Generated by Django 4.2.6 on 2023-10-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0003_film_filmwebrating_film_obraz_film_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=70)),
            ],
        ),
    ]
