# Generated by Django 4.2.6 on 2023-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_osoba'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='filmwebRating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
