# Generated by Django 4.2.7 on 2023-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0004_remove_film_obsada'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='obsada',
            field=models.ManyToManyField(null=True, related_name='filmy', to='Filmy.osoba'),
        ),
    ]
