# Generated by Django 4.2.7 on 2023-11-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0005_film_obsada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='obsada',
        ),
    ]
