# Generated by Django 4.2.7 on 2023-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0006_remove_film_obsada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': 'Filmy'},
        ),
        migrations.AlterModelOptions(
            name='gatunek',
            options={'verbose_name_plural': 'Gatunek Filmu'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name_plural': 'Osoba'},
        ),
        migrations.AddField(
            model_name='film',
            name='po_premierze',
            field=models.BooleanField(default=False),
        ),
    ]
