# Generated by Django 4.2.6 on 2023-10-22 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_film_czas_trwania'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezyser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rezyserowane_filmy', to='filmy.osoba'),
        ),
    ]
