# Generated by Django 4.1.13 on 2023-12-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0009_remove_gatunek_filmy_remove_gatunek_nazwa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='wybierz_gatunek',
            new_name='Gatunki',
        ),
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(3, 'Komedia'), (6, 'Wojenny'), (4, 'SCI-FI'), (0, 'Horror'), (2, 'Fantazy'), (1, 'Dramat'), (7, 'Inne'), (5, 'Kryminał')], default=7),
        ),
    ]
