# Generated by Django 4.2.6 on 2023-10-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0010_film_obsada_gatunek_filmy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunek',
            name='filmy',
        ),
    ]
