# Generated by Django 4.2.6 on 2023-10-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0011_remove_gatunek_filmy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatunek',
            name='filmy',
            field=models.ManyToManyField(related_name='gatunki', to='filmy.film'),
        ),
    ]
