# Generated by Django 4.1.13 on 2023-12-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0012_alter_recenzja_options_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(7, 'Inne'), (2, 'Fantazy'), (3, 'Komedia'), (6, 'Wojenny'), (0, 'Horror'), (1, 'Dramat'), (5, 'Kryminał'), (4, 'SCI-FI')], default=7),
        ),
    ]
