# Generated by Django 4.1.13 on 2023-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0014_alter_osoba_options_osoba_film_many_to_many_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(3, 'Komedia'), (6, 'Wojenny'), (2, 'Fantazy'), (4, 'SCI-FI'), (5, 'Kryminał'), (7, 'Inne'), (0, 'Horror'), (1, 'Dramat')], default=7),
        ),
    ]
