# Generated by Django 4.1.13 on 2023-12-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0015_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(0, 'Horror'), (2, 'Fantazy'), (6, 'Wojenny'), (5, 'Kryminał'), (1, 'Dramat'), (3, 'Komedia'), (7, 'Inne'), (4, 'SCI-FI')], default=7),
        ),
    ]
