# Generated by Django 4.1.13 on 2023-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0016_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(3, 'Komedia'), (7, 'Inne'), (0, 'Horror'), (1, 'Dramat'), (6, 'Wojenny'), (5, 'Kryminał'), (4, 'SCI-FI'), (2, 'Fantazy')], default=7),
        ),
    ]
