# Generated by Django 4.1.13 on 2023-12-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0017_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='Gatunki',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='Filmy.gatunek'),
        ),
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(2, 'Fantazy'), (3, 'Komedia'), (5, 'Kryminał'), (4, 'SCI-FI'), (7, 'Inne'), (1, 'Dramat'), (0, 'Horror'), (6, 'Wojenny')], default=7),
        ),
    ]
