# Generated by Django 4.1.13 on 2023-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0018_alter_film_gatunki_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(1, 'Dramat'), (7, 'Inne'), (6, 'Wojenny'), (0, 'Horror'), (4, 'SCI-FI'), (3, 'Komedia'), (5, 'Kryminał'), (2, 'Fantazy')], default=7),
        ),
    ]
