# Generated by Django 4.1.13 on 2023-12-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmy', '0019_alter_gatunek_gatunek_filmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_filmu',
            field=models.IntegerField(choices=[(6, 'Wojenny'), (3, 'Komedia'), (1, 'Dramat'), (5, 'Kryminał'), (7, 'Inne'), (2, 'Fantazy'), (4, 'SCI-FI'), (0, 'Horror')], default=7),
        ),
    ]
